- id: GL001
  alias: Tuinverlichting uit bij zonsopkomst
  trigger:
  - event: sunrise
    platform: sun
  action:
    service: homeassistant.turn_off
    entity_id: group.tuinverlichting
- id: GL002
  alias: Tuinverlichting aan bij zonsondergang
  trigger:
  - event: sunset
    platform: sun
  action:
    service: homeassistant.turn_on
    entity_id: group.tuinverlichting
- id: KW001
  alias: Keukenraam lamp aan bij zonsondergang
  trigger:
    platform: sun
    event: sunset
    offset: -00:15:00
  action:
    service: homeassistant.turn_on
    entity_id: switch.keukenraam_lamp
- id: KW002
  alias: Keukenraam lamp uit om 0:30
  trigger:
    platform: time
    at: 00:30:00
  action:
    service: homeassistant.turn_off
    entity_id: switch.keukenraam_lamp
- id: BR001
  alias: Takken aan bij zonsondergang
  trigger:
    platform: sun
    event: sunset
    offset: -00:20:00
  action:
    service: homeassistant.turn_on
    entity_id: switch.takken
- id: BR002
  alias: Takken uit om 1:00
  trigger:
    platform: time
    at: 01:00:00
  action:
    service: homeassistant.turn_off
    entity_id: switch.takken
- id: TL001
  alias: Toilet verlichting aan bij open deur
  trigger:
  - entity_id: binary_sensor.ac_11f8af2_10
    platform: state
    to: 'on'
  action:
  - entity_id: switch.toilet_lampen
    service: homeassistant.turn_on
  mode: single
- id: TL002
  alias: Toilet verlichting uit bij gesloten deur
  trigger:
  - entity_id: binary_sensor.ac_11f8af2_10
    platform: state
    to: 'off'
  action:
  - entity_id: switch.toilet_lampen
    service: homeassistant.turn_off
  mode: single



- id: TW001
  alias: Trap spot aan status
  trigger:
    platform: state
    entity_id: switch.washok_1_schakelaar
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.trap_spots

- id: TW002
  alias: Trap spot uit status
  trigger:
    platform: state
    entity_id: switch.washok_1_schakelaar
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.trap_spots

- id: TW003
  alias: Trap schakelaar aan status
  trigger:
    platform: state
    entity_id: light.trap_spots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.washok_1_schakelaar

- id: TW004
  alias: Trap schakelaar uit status
  trigger:
    platform: state
    entity_id: light.trap_spots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.washok_1_schakelaar




######################
# KANTOOR SCHAKELAAR #
######################

########## KANTOOR SPOTS ##########

- id: OW001
  alias: Kantoor lampen aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_relay_left
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.kantoor_spots

- id: OW002
  alias: Kantoor lampen uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_relay_left
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.kantoor_spots

- id: OW003
  alias: Kantoor schakelaar aan status
  trigger:
    platform: state
    entity_id: light.kantoor_spots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_schakelaar_relay_left

- id: OW004
  alias: Kantoor schakelaar uit status
  trigger:
    platform: state
    entity_id: light.kantoor_spots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_schakelaar_relay_left

########## KANTOOR SFEERSPOTS ##########

- id: S2W001
  alias: Kantoor sfeerspots aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_relay_middle
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_sfeerspots

- id: S2W002
  alias: Kantoor sfeerspots uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_relay_middle
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_sfeerspots

- id: S2W003
  alias: Kantoor sfeerspots schakelaar aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_sfeerspots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_schakelaar_relay_middle

- id: S2W004
  alias: Kantoor sfeerspots schakelaar uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_sfeerspots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_schakelaar_relay_middle

########## SALON LAMPEN SCHAKELING ##########

- id: SW001
  alias: Salon lampen aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_relay_right
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.salon_spots

- id: SW002
  alias: Salon lampen uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_relay_right
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.salon_spots

- id: SW003
  alias: Salon schakelaar aan status
  trigger:
    platform: state
    entity_id: light.salon_spots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_schakelaar_relay_right

- id: SW004
  alias: Salon schakelaar uit status
  trigger:
    platform: state
    entity_id: light.salon_spots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_schakelaar_relay_right

########################
# BABYKAMER SCHAKELAAR #
########################

########## BABYKAMER LAMP ##########

- id: BW001
  alias: Babykamer lamp aan status
  trigger:
    platform: state
    entity_id: switch.babykamer_lamp_schakelaar
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.babykamer_lamp

- id: BW002
  alias: Babykamer lamp uit status
  trigger:
    platform: state
    entity_id: switch.babykamer_lamp_schakelaar
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.babykamer_lamp

- id: BW003
  alias: Babykamer schakelaar aan status
  trigger:
    platform: state
    entity_id: light.babykamer_lamp
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.babykamer_lamp_schakelaar

- id: BW004
  alias: Babykamer schakelaar uit status
  trigger:
    platform: state
    entity_id: light.babykamer_lamp
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.babykamer_lamp_schakelaar

- id: BF001
  alias: Babykamer vloerlamp aan status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen_schakelaar
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.babykamer_vloerlampen
- id: BF002
  alias: Babykamer vloerlamp uit status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen_schakelaar
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.babykamer_vloerlampen
- id: BF003
  alias: Babykamer vloerlamp schakelaar aan status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.babykamer_vloerlampen_schakelaar
- id: BF004
  alias: Babykamer vloerlamp schakelaar uit status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.babykamer_vloerlampen_schakelaar








- alias: Set washing machine active when power detected
  trigger:
  - platform: numeric_state
    entity_id: sensor.wasmachine_wattage
    above: 10
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: sensor.wasmachine_status
      state: Standby
    - condition: state
      entity_id: sensor.wasmachine_status
      state: Schoon
    - condition: state
      entity_id: sensor.wasmachine_status
      state: Afronden
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.wasmachine_status
      option: Bezig

      
  id: c6e06bb205224ae3bb9b94b2f105b33e
- alias: Set washing machine finished when power drops
  trigger:
  - platform: numeric_state
    entity_id: sensor.wasmachine_wattage
    below: 6
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.wasmachine_status
      state: Bezig
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.wasmachine_status
      option: Afronden


  id: 3bb94ebcac104df69f6d4a1cc2db69d2
- alias: Set washing machine clean after timeout
  trigger:
  - platform: state
    entity_id: input_select.wasmachine_status
    to: Afronden
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.wasmachine_status
      state: Afronden
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.wasmachine_status
      option: Schoon

  id: 090fee16c5664a3da309fb29e709e236
- alias: Send alert when washing machine is clean
  trigger:
  - platform: state
    entity_id: sensor.wasmachine_status
    to: Schoon
  action:
  - service: notify.pushover
    data:
      message: Ahoy, maatjes! De wasmachine is klaar.
      title: Wasmachine
      data:
        sound: tugboat
        priority: 0



  id: 89dfa501834b4e90b73530ffd1849d1b
- alias: Set dryer active when power detected
  trigger:
  - platform: numeric_state
    entity_id: sensor.droger_wattage
    above: 10
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: sensor.droger_status
      state: Standby
    - condition: state
      entity_id: sensor.droger_status
      state: Droog
    - condition: state
      entity_id: sensor.droger_status
      state: Afronden
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.droger_status
      option: Bezig
  id: DR0001

- alias: Set dryer finished when power drops
  trigger:
  - platform: numeric_state
    entity_id: sensor.droger_wattage
    below: 6
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.droger_status
      state: Bezig
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.droger_status
      option: Afronden

  id: DR0002
- alias: Set dryer dry after timeout
  trigger:
  - platform: state
    entity_id: input_select.droger_status
    to: Afronden
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.droger_status
      state: Afronden
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.droger_status
      option: Droog

  id: DR0003
- alias: Send alert when dryer is dry
  trigger:
  - platform: state
    entity_id: sensor.droger_status
    to: Droog
  action:
  - service: notify.pushover
    data:
      message: Alarm! De droger is gereed.
      title: Droger
      data:
        sound: incoming
        priority: 0
  - service: homeassistant.turn_off
    entity_id: switch.droger








  id: DR0004
- alias: Leave Work notification
  trigger:
  - platform: zone
    event: leave
    zone: zone.work
    entity_id: device_tracker.django_mobile
  action:
  - service: notify.pushover
    data:
      message: Alert! Django left IBS
      title: Location
      data:
        sound: incoming
        priority: 0
  id: ZN0001
- alias: Enter Highway
  trigger:
  - platform: zone
    event: leave
    zone: zone.highway
    entity_id: device_tracker.django_mobile
  action:
  - service: notify.pushover
    data:
      message: Alert! Django enters the Highway
      title: Location
      data:
        sound: incoming
        priority: 0
  id: ZN0002
