- id: '1615124666052'
  alias: New Automation
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.keuken_sensor
      light_target:
        entity_id:
        - light.keuken_spots
