
#---------------------------------MAIN SYSTEM----------------------------------#

default_config:

homeassistant:
  customize_domain: !include customize/customize_domain.yaml

http: 
  use_x_forwarded_for: true 
  trusted_proxies: !secret trusted_proxy
  login_attempts_threshold: 3

#--------------------------CUSTOMISATION & AUTOMATION--------------------------#

group: !include groups.yaml
automation: !include_dir_merge_list automation

#----------------------------------SELECTORS-----------------------------------#

input_select: !include platforms/options.yaml

#-------------------------HARDWARE & SOFTWARE PLATFORMS------------------------#

nest: !include platforms/nest.yaml
google_assistant: !include platforms/google_assistant.yaml
tts: !include platforms/google_translate.yaml
spotify: !include platforms/spotify.yaml

#------------------------------------LIGHTS------------------------------------#

light: !include devices/lights/milights.yaml

#-----------------------------------SENSORS------------------------------------#

sensor: !include devices/sensors/sensors.yaml
