
# ------------------------------ Default config ------------------------------ #

default_config:

# ------------------------------- Main system -------------------------------- #

homeassistant:
  customize_domain: !include customize/customize_domain.yaml

http: 
  use_x_forwarded_for: true 
  trusted_proxies: !secret trusted_proxy
  login_attempts_threshold: 3

recorder:
  db_url: !secret db_url

# ------------------------ Customisation & automation ------------------------ #

automation: !include automations.yaml
script: !include scripts.yaml

# ------------------------------- Integrations ------------------------------- #

tts: !include integrations/google_translate.yaml
rest_command: !include integrations/rest_commands.yaml

# ---------------------------------- Lights ---------------------------------- #

# The Mi-lights are going to be fased out and will be decremented!
light: !include devices/lights/milights.yaml
