
#--------------------------------DEFAULT CONFIG--------------------------------#

# default_config:
application_credentials:
automation:
counter:
dhcp:
energy:
frontend:
history:
input_boolean:
input_button:
input_datetime:
input_number:
input_text:
logbook:
map:
media_source:
mobile_app:
my:
network:
person:
scene:
script:
ssdp:
sun:
system_health:
tag:
timer:
usb:
webhook:
zeroconf:
zone:

#---------------------------------MAIN SYSTEM----------------------------------#

homeassistant:
  customize_domain: !include customize/customize_domain.yaml

http: 
  use_x_forwarded_for: true 
  trusted_proxies: !secret trusted_proxy
  login_attempts_threshold: 3

#--------------------------CUSTOMISATION & AUTOMATION--------------------------#

automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml

#----------------------------------SELECTORS-----------------------------------#

input_select: !include platforms/options.yaml

#-------------------------HARDWARE & SOFTWARE PLATFORMS------------------------#

tts: !include platforms/google_translate.yaml

#------------------------------------LIGHTS------------------------------------#

light: !include devices/lights/milights.yaml

#-----------------------------------SENSORS------------------------------------#

sensor: !include devices/sensors/sensors.yaml
