### MAIN SYSTEM ###
homeassistant:

  name: Homebase
  latitude: !secret home_latitude
  longitude: !secret home_longtitude
  unit_system: metric
  time_zone: Europe/Amsterdam

  customize_domain: !include customize/customize_domain.yaml

default_config:

### LOGGING, UPDATING AND DEVICE DISCOVERING ###
system_health:
logbook:
history:
updater:
discovery:
stream:

### CUSTOMISATION ###
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

### WEATHER AND LOCATIONS ###
weather:
sun:
map:

### SELECTORS ###
input_select: !include platforms/options.yaml

### HARDWARE & SOFTWARE PLATFORMS ###
zha: !include platforms/zigbee.yaml
rfxtrx: !include platforms/rfxcom.yaml
nest: !include platforms/nest.yaml
nissan_leaf: !include platforms/nissan.yaml

### LIGHTS ###
light: !include devices/lights/milights.yaml

### SENSORS ###
sensor: !include devices/sensors/sensors.yaml
