### MAIN SYSTEM ###
homeassistant:

  name: Homebase
  latitude: !secret home_latitude
  longitude: !secret home_longtitude
  unit_system: metric
  time_zone: Europe/Amsterdam

  customize: !include customize/customize.yaml
  customize_domain: !include customize/customize_domain.yaml
  customize_glob: !include customize/customize_glob.yaml

default_config:

### LOGGING, UPDATING AND DEVICE DISCOVERING ###
system_health:
logbook:
history:
updater:
discovery:
stream:

### CUSTOMISATION ###
group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

### WEATHER AND LOCATIONS ###
weather: !include platforms/weather.yaml
sun:
map:

### NOTIFIERS ###
input_select: !include platforms/options.yaml
notify: !include platforms/notify.yaml

### HARDWARE PLATFORMS ###
rfxtrx: !include platforms/rfxcom.yaml
nissan_leaf: !include platforms/nissan.yaml

### LIGHTS ###
light 1: !include devices/lights/milights.yaml

### SENSORS ###
sensor: !include devices/sensors/sensors.yaml

### INFLUXDB ####
influxdb:
  host: 192.168.1.150
  port: 8086
  database: homeassistant
  username: homeassistant
  password: test
  max_retries: 3
  default_measurement: state