### MAIN SYSTEM ###
homeassistant:

  name: Homebase
  latitude: !secret home_latitude
  longitude: !secret home_longtitude
  unit_system: metric
  time_zone: Europe/Amsterdam

  customize: !include customize/customize.yaml
  customize_domain: !include customize/customize_domain.yaml
  customize_glob: !include customize/customize_glob.yaml

default_config:

http: !include http.yaml

### LOGGING, UPDATING AND DEVICE DISCOVERING ###
system_health:
logbook:
history:
updater:
discovery:
stream:

### CUSTOMISATION ###
group: !include groups.yaml
automation: !include automations.yaml
#automation: !include_dir_merge_list automation
script: !include scripts.yaml

### WEATHER AND LOCATIONS ###
sun:
weather: !include platforms/weather.yaml
map:

### NOTIFIERS ###
input_select: !include platforms/options.yaml
notify: !include platforms/notify.yaml
tts: !include platforms/google_tts.yaml

### HARDWARE PLATFORMS ###
rfxtrx: !include platforms/rfxcom.yaml
google_assistant: !include platforms/google_assistant.yaml
nissan_leaf: !include platforms/nissan.yaml

### LIGHTS ###
light 1: !include devices/lights/milights.yaml

### SENSORS ###
sensor: !include devices/sensors/sensors.yaml

### INFLUXDB ####
influxdb:
  host: 192.168.1.150
  port: 8086
  database: homeassistant
  username: homeassistant
  password: test
  max_retries: 3
  default_measurement: state