
# ----------------------------- Closet lights on ----------------------------- #

# Turn the walk-in closet lamp on when motion is detected
- alias: Inloopkast bewegingssensor
  trigger:
  - type: motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.walk_in_closet_sensor_occupancy
    domain: binary_sensor
    for:
      seconds: 1
  action:
  - service: homeassistant.turn_on
    entity_id: light.walk_in_closet_spots

# ---------------------------- Closet lights off ----------------------------- #

# Turn the walk-in closet lamp off when NO motion is detected
- alias: Inloopkast geen beweging
  trigger:
  - type: no_motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.walk_in_closet_sensor_occupancy
    domain: binary_sensor
    for:
      seconds: 1
  action:
  - service: homeassistant.turn_off
    entity_id: light.walk_in_closet_spots
