
# ----------------------------- Closet lights on ----------------------------- #

# Turn the stair closet lamp on when the door is opened
- alias: Trapkast deur open
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.stair_closet_sensor_contact
    from: 'off'
    platform: state
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.trapkast_lamp

# ---------------------------- Closet lights off ----------------------------- #

# Turn the stairs closet lamp off when the door is closed
- alias: Trapkast deur gesloten
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.stair_closet_sensor_contact
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.trapkast_lamp
