
# ----------------------------- Kitchen spots on ----------------------------- #

# Turn the kitchen spots on when motion is detected
- alias: Keuken bewegingssensor
  trigger:
  - type: motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.kitchen_sensor_occupancy
    domain: binary_sensor
    for:
      seconds: 2
  action:
  - service: homeassistant.turn_on
    entity_id: light.kitchen_spots

# ----------------------------- Kitchen spots off ---------------------------- #

# Turn the kitchen spots off when NO motion is detected
- alias: Keuken geen beweging
  trigger:
  - type: no_motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.kitchen_sensor_occupancy
    domain: binary_sensor
    for:
      seconds: 3
  action:
  - service: homeassistant.turn_off
    entity_id: light.kitchen_spots
