
#---------------------------3 MILIGHT DEVICES, 1 HOST--------------------------#

- platform: limitlessled
  bridges:
   - host: 192.168.5.245
     groups:
     - number: 2
       type: rgbww
       name: Trap spots
     - number: 3
       type: rgbww
       name: Kantoor spots
     - number: 4
       type: rgbww
       name: Studio spots
