### 5 MILIGHT DEVICES, 2 HOSTS ###
- platform: limitlessled
  bridges:
   - host: 192.168.1.142
     groups:
     - number: 2
       type: rgbww
       name: Trap spots
     - number: 3
       type: rgbww
       name: Kantoor spots
     - number: 4
       type: rgbww
       name: Salon spots
