
# ----------------------------- Garden lights on ----------------------------- #

# Turn the garden lights on at sundown
- alias: Tuinverlichting zonsondergang
  trigger:
  - event: sunset
    platform: sun
  action:
    service: homeassistant.turn_on
    entity_id: switch.garden_lights

# ---------------------------- Garden lights off ----------------------------- #

# Turn the garden lights off at sunrise
- alias: Tuinverlichting zonsopkomst
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: switch.garden_lights
