# Turn the kitchen window lamp on 15 minutes before sundown.
- alias: Keukenraam zonsondergang aan
  trigger:
    platform: sun
    event: sunset
    offset: -00:15:00
  action:
    service: homeassistant.turn_on
    entity_id: switch.keukenraam_lamp

# Turn the kitchen window lamp off at 12:30 AM
- alias: Keukenraam schakelklok
  trigger:
    platform: time
    at: 00:30:00
  action:
    service: homeassistant.turn_off
    entity_id: switch.keukenraam_lamp