# Turn the kitchen spots on when motion is detected.
- alias: Keuken bewegingssensor
  trigger:
  - type: motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.keuken_sensor
    domain: binary_sensor
    for:
      seconds: 2
  action:
  - service: homeassistant.turn_on
    entity_id: light.keuken_spots

# Turn the kitchen spots off when NO motion is detected.
- alias: Keuken geen beweging
  trigger:
  - type: no_motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.keuken_sensor
    domain: binary_sensor
    for:
      seconds: 3
  action:
  - service: homeassistant.turn_off
    entity_id: light.keuken_spots