# Turn the toilet spots on when motion is detected.
- alias: Toilet bewegingssensor
  trigger:
  - type: motion
    platform: device
    device_id: ac2b262c05b111ebb642d12a10912f97
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
    for:
      seconds: 3
  action:
  - type: turn_on
    device_id: a084e2ad152711ebb5951536f60f7f42
    entity_id: switch.toilet_sfeerspots
    domain: switch
  mode: single

# Turn the toilet spots off when no motion is detected for 5 minutes.
- alias: Toilet geen beweging
  trigger:
  - type: no_motion
    platform: device
    device_id: ac2b262c05b111ebb642d12a10912f97
    entity_id: binary_sensor.toilet_sensor
    domain: binary_sensor
    for:
      minutes: 5
  condition:
  - condition: device
    type: is_on
    device_id: a084e2ad152711ebb5951536f60f7f42
    entity_id: switch.toilet_sfeerspots
    domain: switch
  action:
  - type: turn_off
    device_id: a084e2ad152711ebb5951536f60f7f42
    entity_id: switch.toilet_sfeerspots
    domain: switch
  mode: single