
#-------------------------WASHING MACHINE STATUS SENSOR------------------------#

- platform: template
  sensors:
    wasmachine_status:
      value_template: '{{ states.input_select.wasmachine_status.state}}'
      friendly_name: 'Wasmachine status'

#-----------------------------DRYER STATUS SENSOR------------------------------#

- platform: template
  sensors:
    droger_status:
      value_template: '{{ states.input_select.droger_status.state}}'
      friendly_name: 'Droger status'
