# When the left switch is pressed turn the babyroom lamp on
- alias: Babykamer lamp aan status
  trigger:
    platform: state
    entity_id: switch.babykamer_lamp_schakelaar
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.babykamer_lamp

# When the left switch is pressed turn the babyroom lamp off
- alias: Babykamer lamp uit status
  trigger:
    platform: state
    entity_id: switch.babykamer_lamp_schakelaar
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.babykamer_lamp

# When the app is used turn the babyroom lamp on
- alias: Babykamer schakelaar aan status
  trigger:
    platform: state
    entity_id: light.babykamer_lamp
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.babykamer_lamp_schakelaar

# When the app is used turn the babyroom lamp off
- alias: Babykamer schakelaar uit status
  trigger:
    platform: state
    entity_id: light.babykamer_lamp
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.babykamer_lamp_schakelaar


# When the right switch is pressed turn the babyroom vloorlamp on
- alias: Babykamer vloerlamp aan status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen_schakelaar
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.babykamer_vloerlampen

# When the right switch is pressed turn the babyroom vloorlamp off
- alias: Babykamer vloerlamp uit status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen_schakelaar
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.babykamer_vloerlampen

# When the app is used turn the babyroom vloorlamp on
- alias: Babykamer vloerlamp schakelaar aan status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.babykamer_vloerlampen_schakelaar

# When the app is used turn the babyroom vloorlamp off
- alias: Babykamer vloerlamp schakelaar uit status
  trigger:
    platform: state
    entity_id: switch.babykamer_vloerlampen
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.babykamer_vloerlampen_schakelaar