# When the dryer  uses above the 10 Watts of usage set the state to "Bezig"
- alias: Droger status bezig
  trigger:
  - platform: numeric_state
    entity_id: sensor.droger_wattage
    above: 10
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: sensor.droger_status
      state: Standby
    - condition: state
      entity_id: sensor.droger_status
      state: Droog
    - condition: state
      entity_id: sensor.droger_status
      state: Afronden
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.droger_status
      option: Bezig

# When the dryer hits below the 6 Watts of usage change the status to "Afronden"
- alias: Droger status afronden
  trigger:
  - platform: numeric_state
    entity_id: sensor.droger_wattage
    below: 6
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.droger_status
      state: Bezig
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.droger_status
      option: Afronden

# set a countdown for 2 minutes when the drayer is on "Afronden", after 2 minutes change the state to "Droog"
- alias: Droger status droog
  trigger:
  - platform: state
    entity_id: input_select.droger_status
    to: Afronden
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.droger_status
      state: Afronden
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.droger_status
      option: Droog

# Sends a pushover alert to mobile when the dryer status is changed to "Droog".
- alias: Droger status melding
  trigger:
  - platform: state
    entity_id: sensor.droger_status
    to: Droog
  action:
  - service: notify.pushover
    data:
      message: De droger is gereed!
      title: Droger
      data:
        sound: incoming
        priority: 0
  - service: homeassistant.turn_off
    entity_id: switch.droger

# Sets the dryer status to "Standby" when it is switched on from an off state.
- alias: Droger status standby
  trigger:
  - platform: state
    entity_id: switch.droger
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: sensor.droger_status
      state: Droog
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.droger_status
      option: Standby