# When the left switch is pressed turn the office spots on
- alias: Kantoor lampen aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_left
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.kantoor_spots

# When the left switch is pressed turn the office spots off
- alias: Kantoor lampen uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_left
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.kantoor_spots

# When the app is used turn the office spots on
- alias: Kantoor schakelaar aan status
  trigger:
    platform: state
    entity_id: light.kantoor_spots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_schakelaar_left

# When the app is used turn the office spots off
- alias: Kantoor schakelaar uit status
  trigger:
    platform: state
    entity_id: light.kantoor_spots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_schakelaar_left


# When the middle switch is pressed turn the office mini spots on
- alias: Kantoor sfeerspots aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_middle
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_sfeerspots

# When the middle switch is pressed turn the office mini spots off
- alias: Kantoor sfeerspots uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_middle
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_sfeerspots

# When the app is used turn the office mini spots on
- alias: Kantoor sfeerspots schakelaar aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_sfeerspots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_schakelaar_middle

# When the app is used turn the office mini spots off
- alias: Kantoor sfeerspots schakelaar uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_sfeerspots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_schakelaar_middle


# When the right switch is pressed turn the salon spots on
- alias: Salon lampen aan status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_right
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.salon_spots

# When the right switch is pressed turn the salon spots off
- alias: Salon lampen uit status
  trigger:
    platform: state
    entity_id: switch.kantoor_schakelaar_right
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.salon_spots

# When the app is used turn the salon spots on
- alias: Salon schakelaar aan status
  trigger:
    platform: state
    entity_id: light.salon_spots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kantoor_schakelaar_right

# When the app is used turn the salon spots off
- alias: Salon schakelaar uit status
  trigger:
    platform: state
    entity_id: light.salon_spots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kantoor_schakelaar_right