# When the right switch is pressed turn the room spots on
- alias: Anakin's lampen aan status
  trigger:
    platform: state
    entity_id: switch.anakins_switch_right
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.anakins_lamp

# When the right switch is pressed turn the room spots off
- alias: Anakin's lampen uit status
  trigger:
    platform: state
    entity_id: switch.anakins_switch_right
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.anakins_lamp

# When the app is used turn the room spots on
- alias: Anakin's schakelaar aan status
  trigger:
    platform: state
    entity_id: light.anakins_lamp
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.anakins_switch_right

# When the app is used turn the room spots off
- alias: Anakin's schakelaar uit status
  trigger:
    platform: state
    entity_id: light.anakins_lamp
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.anakins_switch_right
