# Turn the branches on 20 minutes before sundown.
- alias: Takken zonsondergang aan
  trigger:
    platform: sun
    event: sunset
    offset: -00:20:00
  action:
    service: homeassistant.turn_on
    entity_id: switch.takken

# Turn the branches off at 01:00 AM
- alias: Takken schakelklok
  trigger:
    platform: time
    at: 01:00:00
  action:
    service: homeassistant.turn_off
    entity_id: switch.takken