# Turn the stair closet lamp on when motion is detected.
- alias: Trapkast bewegingssensor
  trigger:
  - type: motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.trapkast_sensor
    domain: binary_sensor
    for:
      seconds: 1
  action:
  - service: homeassistant.turn_on
    entity_id: light.trapkast_lamp

# Turn the stairs closet lamp off when NO motion is detected.
- alias: Trapkast geen beweging
  trigger:
  - type: no_motion
    platform: device
    device_id: b71e2792fd7ec4f532ff3f5671b41417
    entity_id: binary_sensor.trapkast_sensor
    domain: binary_sensor
    for:
      seconds: 1
  action:
  - service: homeassistant.turn_off
    entity_id: light.trapkast_lamp