# When the left switch is pressed turn the upstairs spots on
- alias: Boventrap spots aan status
  trigger:
    platform: state
    entity_id: switch.boventrap_spots_schakelaar
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: light.trap_spots

# When the left switch is pressed turn the upstairs spots off
- alias: Boventrap spots uit status
  trigger:
    platform: state
    entity_id: switch.boventrap_spots_schakelaar
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: light.trap_spots

# When the app is used turn the upstairs spot on
- alias: Boventrap schakelaar aan status
  trigger:
    platform: state
    entity_id: light.trap_spots
    to: 'on'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.boventrap_spots_schakelaar

# When the app is used turn the upstairs spot off
- alias: Boventrap schakelaar uit status
  trigger:
    platform: state
    entity_id: light.trap_spots
    to: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.boventrap_spots_schakelaar