esphome:
  name: bluetooth-hub
  platform: ESP32
  board: esp32doit-devkit-v1

# esp8266:
#   board: nodemcuv2

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:

ota:
  password: "224c14826fd2a8216b926efc1f0385b5"

wifi:
  ssid: Motherbase
  password: "RK628AwnBx48Y2h553z25V7M"

esp32_ble_tracker:
