esphome:
  name: lock-trapluik
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret IoT_ssid
  password: !secret IoT_password

logger:

api:
  encryption: 
    key: 'Vm4u9qacc2AXOU15/py0Sd7n9goZehFYmZWMA+SqIBw='

ota:
  password: !secret esphome_ota

switch:
  - platform: gpio
    name: Trapluik
    id: relay
    pin: GPIO12
    inverted: true
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    output: green_led
    id: led
