esphome:
  name: minispots-zolder
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret IoT_ssid
  password: !secret IoT_password

logger:

api:
  encryption: 
    key: "/7to4WKEPz/gx+LJ6zuf9ghqLdFDMhwqeY1wFT/fsK8="

ota:
  password: !secret esphome_ota

switch:
  - platform: gpio
    name: Zolder spots
    id: relay
    pin: GPIO12
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    output: green_led
    id: led
