substitutions:
  name: "speaker-childroom"
packages:
  raspiaudio.muse-luxe: github://esphome/media-players/raspiaudio-muse-luxe.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
