esphome:
  name: wasruimteschakelaar
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret IoT_ssid
  password: !secret IoT_password
  manual_ip:
    static_ip: 192.168.10.21
    gateway: 192.168.10.1
    subnet: 255.255.255.0
    dns1: 192.168.10.1
    dns2: 0.0.0.0

logger:

api:
  password: !secret esphome_api

ota:
  password: !secret esphome_ota

switch:
  - platform: gpio
    name: Boventrap spots schakelaar
    id: relay1
    pin: GPIO12
  - platform: gpio
    name: Wasruimte spots schakelaar
    id: relay2
    pin: GPIO5

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Boventrap spots schakelaar"
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: True
    name: "Wasruimte spots schakelaar"
    on_press:
      - switch.toggle: relay2

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO13
      inverted: True